/**
 * Generates docs/TOOLS.md — the complete tool reference — from the live tool registry
 * (names, titles, descriptions, input fields), grouped by family.
 *   npx tsx scripts/gen-tool-reference.ts            write docs/TOOLS.md
 *   npx tsx scripts/gen-tool-reference.ts --summary  print "family: n tools" lines
 */

import { writeFileSync } from "node:fs";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";

import { ArchicadClient } from "../src/archicad/client.js";
import { TOOL_FAMILIES } from "../src/tools/index.js";

interface JsonSchema {
  type?: string | string[];
  description?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  enum?: unknown[];
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
}

function typeOf(s: JsonSchema | undefined): string {
  if (!s) return "any";
  if (s.enum) return s.enum.map((e) => JSON.stringify(e)).join(" \\| ");
  const alts = s.anyOf ?? s.oneOf;
  if (alts) return [...new Set(alts.map(typeOf))].join(" \\| ");
  if (s.type === "array") return `${typeOf(s.items)}[]`;
  if (s.type === "object" && s.properties) return "object";
  return Array.isArray(s.type) ? s.type.join("|") : (s.type ?? "any");
}

function oneLine(text = ""): string {
  return text.replace(/\s+/g, " ").replace(/\|/g, "\\|").trim();
}

const ctx = { ac: new ArchicadClient({ port: 19723 }) };
const summary = process.argv.includes("--summary");
let md = `# Tool reference\n\nGenerated by \`npx tsx scripts/gen-tool-reference.ts\` from the server's tool registry. ` +
  `Units: meters and degrees. Elements are referenced by GUID.\n\n`;
const toc: string[] = [];
const sections: string[] = [];
let total = 0;

for (const [family, register] of TOOL_FAMILIES) {
  const server = new McpServer({ name: "ref", version: "1" });
  register(server, ctx);
  const [a, b] = InMemoryTransport.createLinkedPair();
  await server.connect(b);
  const client = new Client({ name: "ref", version: "1" });
  await client.connect(a);
  // A family without tools registers no tools/list handler ("Method not found").
  const tools = await client.listTools().then((r) => r.tools, () => []);
  await client.close();
  total += tools.length;
  if (summary) {
    console.log(`${family}: ${tools.length} tools`);
    continue;
  }
  toc.push(`- [${family}](#${family}) (${tools.length})`);
  let sec = `## ${family}\n\n`;
  for (const t of tools) {
    const input = t.inputSchema as JsonSchema;
    sec += `### \`${t.name}\`\n\n${t.description ?? ""}\n\n`;
    const rows: string[] = [];
    // Flattens nested objects / arrays of objects into dotted paths (walls[].begin, threeD.camera ...).
    const isPoint = (x: JsonSchema | undefined) => !!x?.properties && Object.keys(x.properties).every((k) => k === "x" || k === "y" || k === "z");
    const walk = (schema: JsonSchema, prefix: string, depth: number) => {
      if (isPoint(schema)) return;
      for (const [name, p] of Object.entries(schema.properties ?? {})) {
        const path = prefix ? `${prefix}.${name}` : name;
        rows.push(`| \`${path}\` | ${oneLine(typeOf(p))} | ${schema.required?.includes(name) ? "yes" : ""} | ${oneLine(p.description)} |`);
        if (depth >= 2) continue;
        const item = p.type === "array" ? p.items : undefined;
        const objectAlt = (p.anyOf ?? p.oneOf)?.find((a) => a.type === "object" && a.properties);
        if (item?.properties) walk(item, `${path}[]`, depth + 1);
        else if (p.properties) walk(p, path, depth + 1);
        else if (objectAlt) walk(objectAlt, path, depth + 1);
      }
    };
    walk(input, "", 0);
    if (rows.length) sec += `| Field | Type | Required | Description |\n|---|---|---|---|\n${rows.join("\n")}\n\n`;
  }
  sections.push(sec);
}

if (summary) {
  console.log(`total: ${total}`);
} else {
  md += `${total} tools in ${TOOL_FAMILIES.length} families.\n\n${toc.join("\n")}\n\n${sections.join("\n")}`;
  writeFileSync("docs/TOOLS.md", md);
  console.log(`docs/TOOLS.md written (${total} tools)`);
}
